export enum ESortBy {
  Id = 'id',
  Name = 'name',
  Surname = 'surname',
  Email = 'email',
  Phone = 'phone',
  Age = 'age',
  Course = 'course',
  CourseFormat = 'course_format',
  CourseType = 'course_type',
  Status = 'status',
  Sum = 'sum',
  AlreadyPaid = 'alreadyPaid',
  Group = 'group',
  CreatedAt = 'created_at',
  Utm = 'utm',
  Msg = 'msg',
  Manager = 'manager',
}
