export const ExcelColumnHeaders = {
  ID: 'ID',
  Name: 'Name',
  Surname: 'Surname',
  Email: 'Email',
  Phone: 'Phone',
  Age: 'Age',
  Course: 'Course',
  CourseFormat: 'Course Format',
  CourseType: 'Course Type',
  Status: 'Status',
  Sum: 'Sum',
  AlreadyPaid: 'Already Paid',
  Group: 'Group',
  CreatedAt: 'Created At',
  UTM: 'UTM',
  Message: 'Message',
  Manager: 'Manager',
  Comment: 'Comment',
};
